openapi: 3.0.0
info:
  description: OSBuild Management
  version: 1.0.0
  title: OSBuildManagement
  contact:
    name: Flotta flotta
    url: https://github.com/project-flotta
    email: flotta@redhat.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: osbuilconfig
    description: OSBuildConfig CRD
paths:
  "/api/osbuild/v1/namespaces/{namespace}/osbuildconfig/{name}/webhooks":
    post:
      description: Triggering webhook builds for OSBuildConfig CRs
      operationId: TriggerBuild
      tags:
        - osbuilconfig
      parameters:
        - in: path
          name: namespace
          description: OSBuilfConfig namespace name
          required: true
          schema:
            type: string
        - in: path
          name: name
          description: OSBuildConfig name
          required: true
          schema:
            type: string
        - in: header
          name: secret
          description: The secret value of the secret with a key named WebHookSecretKey that the webhook definition reference to. The secret ensures the uniqueness of the URL, preventing others from triggering the build
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/message-response"
        "208":
          description: Already Reported
        "400":
          description: Error
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Error
        "500":
          description: Error
components:
  schemas:
    message-response:
      type: object
      properties:
        message_id:
          type: string
        directive:
          type: string
        content:
          description: Content