// Code generated by MockGen. DO NOT EDIT.
// Source: osbuild.go

// Package manifests is a generated GoMock package.
package manifests

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/project-flotta/osbuild-operator/api/v1alpha1"
)

// MockOSBuildCRCreator is a mock of OSBuildCRCreator interface.
type MockOSBuildCRCreator struct {
	ctrl     *gomock.Controller
	recorder *MockOSBuildCRCreatorMockRecorder
}

// MockOSBuildCRCreatorMockRecorder is the mock recorder for MockOSBuildCRCreator.
type MockOSBuildCRCreatorMockRecorder struct {
	mock *MockOSBuildCRCreator
}

// NewMockOSBuildCRCreator creates a new mock instance.
func NewMockOSBuildCRCreator(ctrl *gomock.Controller) *MockOSBuildCRCreator {
	mock := &MockOSBuildCRCreator{ctrl: ctrl}
	mock.recorder = &MockOSBuildCRCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOSBuildCRCreator) EXPECT() *MockOSBuildCRCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOSBuildCRCreator) Create(ctx context.Context, osBuildConfig *v1alpha1.OSBuildConfig, targetImageType v1alpha1.TargetImageType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, osBuildConfig, targetImageType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOSBuildCRCreatorMockRecorder) Create(ctx, osBuildConfig, targetImageType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOSBuildCRCreator)(nil).Create), ctx, osBuildConfig, targetImageType)
}
