# permissions for end users to view osbuildconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osbuildconfig-viewer-role
rules:
- apiGroups:
  - osbuilder.project-flotta.io
  resources:
  - osbuildconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osbuilder.project-flotta.io
  resources:
  - osbuildconfigs/status
  verbs:
  - get
