# permissions for end users to view osbuildenvconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osbuildenvconfig-viewer-role
rules:
- apiGroups:
  - osbuilder.project-flotta.io
  resources:
  - osbuildenvconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osbuilder.project-flotta.io
  resources:
  - osbuildenvconfigs/status
  verbs:
  - get
