# permissions for end users to edit osbuildenvconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osbuildenvconfig-editor-role
rules:
- apiGroups:
  - osbuilder.project-flotta.io
  resources:
  - osbuildenvconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osbuilder.project-flotta.io
  resources:
  - osbuildenvconfigs/status
  verbs:
  - get
