// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package restapi

// MessageResponse defines model for message-response.
type MessageResponse struct {
	// Content
	Content   *interface{} `json:"content,omitempty"`
	Directive *string      `json:"directive,omitempty"`
	MessageId *string      `json:"message_id,omitempty"`
}

// TriggerBuildParams defines parameters for TriggerBuild.
type TriggerBuildParams struct {
	// The secret value of the secret with a key named WebHookSecretKey that the webhook definition reference to. The secret ensures the uniqueness of the URL, preventing others from triggering the build
	Secret string `json:"secret"`
}
