static_resources:
  listeners:
  - name: remote-worker-api
    address:
      socket_address:
        address: 0.0.0.0
        port_value: {{ .WorkerAPIExternalPort }}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: remote_worker_api
          route_config:
            name: local_route
            virtual_hosts:
            - name: app
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: remote-worker-api
                  timeout: {{ .ProxyWorkerAPIUpstreamTimeout }}
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          require_client_certificate: true
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: {{ .ProxyCertsDir }}/{{ .ComposerCertsSecretPublicCertKey }}
              private_key:
                filename: {{ .ProxyCertsDir }}/{{ .ComposerCertsSecretPrivateKeyKey }}
            validation_context:
              trusted_ca:
                filename: {{ .ProxyCertsDir }}/{{ .ComposerCertsSecretCACertKey }}
  - name: composer-api
    address:
      socket_address:
        address: 0.0.0.0
        port_value: {{ .ComposerAPIExternalPort }}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: composer_api
          route_config:
            name: local_route
            virtual_hosts:
            - name: app
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: composer-api
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          require_client_certificate: true
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: {{ .ProxyCertsDir }}/{{ .ComposerCertsSecretPublicCertKey }}
              private_key:
                filename: {{ .ProxyCertsDir }}/{{ .ComposerCertsSecretPrivateKeyKey }}
            validation_context:
              trusted_ca:
                filename: {{ .ProxyCertsDir }}/{{ .ComposerCertsSecretCACertKey }}

  clusters:
  - name: remote-worker-api
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: remote-worker-api
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: {{ .WorkerAPIInternalPort }}
  - name: composer-api
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: composer-api
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: {{ .ComposerAPIInternalPort }}