{{- if .GenericS3 }}
[generic_s3]
{{- else }}
[aws]
{{- end }}
credentials = "/etc/osbuild-worker/{{ .CredentialsFile }}"
bucket = "{{ .Bucket }}"
{{- if .GenericS3 }}
endpoint = "{{ .GenericS3.Endpoint }}"
region = "{{ .GenericS3.Region }}"
{{- if .GenericS3.CABundleFile }}
ca_bundle = "/etc/osbuild-worker/{{ .GenericS3.CABundleFile }}"
{{- end }}
{{- if .GenericS3.SkipSSLVerification }}
skip_ssl_verification = {{ .GenericS3.SkipSSLVerification }}
{{- else }}
skip_ssl_verification = false
{{- end }}
{{- end }}
