apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-cert
  namespace: system
spec:
  isCA: true
  commonName: osbuild-ca
  secretName: root-ca-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
  duration: 87600h # Until we handle rotation, we're setting duration to 10 years
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: osbuild-ca-issuer
  namespace: system
spec:
  ca:
    secretName: root-ca-cert
