---
apiVersion: v1
kind: ConfigMap
metadata:
  name: container-registry-config
data:
  config.yml: |
    version: 0.1
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
        maxthreads: 100
    http:
      addr: 0.0.0.0:5000
    auth:
      htpasswd:
        realm: basic-realm
        path: /etc/docker/registry/auth
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: container-registry-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-registry
  labels:
    app: container-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-registry
  template:
    metadata:
      labels:
        app: container-registry
    spec:
      # imagePullSecrets:
      # - name: docker-io-creds
      containers:
      - name: registry
        image: docker.io/library/registry:2
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-vol
        - mountPath: /etc/docker/registry
          name: registry-config
      volumes:
      - name: registry-config
        projected:
          sources:
          - configMap:
              name: container-registry-config
          - secret:
              name: container-registry-auth
      - name: registry-vol
        persistentVolumeClaim:
          claimName: container-registry-data

---
apiVersion: v1
kind: Service
metadata:
  name: container-registry
spec:
  selector:
    app: container-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: registry
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: container-registry
spec:
  port:
    targetPort: registry
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: container-registry
    weight: 100
