apiVersion: v1
kind: Secret
metadata:
  name: composer-db
  namespace: osbuild
type: Opaque
data:
  host: cG9zdGdyZXNxbA==
  name: Y29tcG9zZXI=
  password: PleaseEnterEncodedPassword
  port: NTQzMg==
  user: Y29tcG9zZXI=
