---
name: CI
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.coverage.outputs.coverage }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Install package
      run: |
        sudo apt-get -y update
        sudo apt-get -y install genisoimage xorriso

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Coverage
      id: coverage
      run: |
        make test-create-coverage
        COVERAGE=$(go tool cover --func=cover.out |  grep total | grep -Eo '[0-9]+\.[0-9]+')
        echo "::set-output name=coverage::${COVERAGE}"

    - uses: actions/upload-artifact@v2
      with:
        name: test-coverage
        path: coverage.html

    - name: Checking generated files are up to date
      run: |
        git diff --quiet api/ config/ controllers/  || (echo "There are not committed changes"; git diff api/ config/ controllers/ | tee; exit 1)

  Coverage:
    needs: build
    name: "Test Coverage ${{ needs.build.outputs.coverage }}"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Coverage status: ${{ needs.build.outputs.coverage }}'
          if [ "$TEST" -lt "0" ]; then echo "Min coverage failed"; exit 1; fi
  Lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.1
        with:
          args: --timeout=2m
